name: Run Benchmarks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Print Environment Info
        run: make print-env
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 21
      - name: Run Benchmarks
        run: make run-benchmarks
